### ISSUE TITLE
[Feature Request] Using DirectWrite to replace GDI

### ISSUE THREAD

**Issue by Masaiki** [pinterf/xy-VSFilter#22] opened 2021-04-23 07:55 UTC
Chinese Japanese and Korean charactors of opentype font (such as Source Han Sans) has a much smaller size when displayed vertically (used like `@Source Han Sans`) on any subtitle filter origin from VSFilter.
Here are samples.
xy-VSFilter+`@source han sans`
![vsfilter_@sourcehansans.png](https://i.loli.net/2021/04/23/f6klj9bnZSEKVwA.png)
libass+`@source han sans`
![libass_@sourcehansans.png](https://i.loli.net/2021/04/23/HZ17wvue3ipgdWC.png)
xy-VSFilter+`source han sans`
![vsfilter_sourcehansans.png](https://i.loli.net/2021/04/23/v75qBj3Ezdr14My.png)
xy-VSFilter+`@noto sans cjk sc regular`
![vsfilter_@notosans.png](https://i.loli.net/2021/04/23/bMglQOWoUF1ZLcH.png)
libass+`@noto sans cjk sc regular`
![libass_@notosans.png](https://i.loli.net/2021/04/23/oJhAP8jcgbI1tK4.png)
xy-VSFilter+`noto sans cjk sc regular`
![vsfilter_notosans.png](https://i.loli.net/2021/04/23/bZGLYXWyCcU7Vfe.png)
[test subtitle file](https://drive.google.com/file/d/1o1driy5JIrhrBdgWRL2Xy8QOqbw227Ie/view?usp=sharing)

**Comment by Masaiki** [comment] 2021-05-05 10:19
https://github.com/Masaiki/VSFilterMod/commit/c09ecfd91224699f6df19ef65f0bbc8cf49a4620
this is an test implementation of replacing gdi with Directwrite(font size, position and etc. display wrong). maybe it will help.

**Comment by pinterf** [comment] 2021-05-05 12:16
Thanks, as a side note, due to other works in my queue you'll experience long delays in my reaction time.

**Comment by clsid2** [comment] 2021-05-15 21:20
I am curious if this would also improve rendering performance.

Here is an example where GDI is very slow with a specific font:
https://github.com/clsid2/mpc-hc/issues/1095

**Comment by Masaiki** [comment] 2021-05-16 00:46
> I am curious if this would also improve rendering performance.
> 
> Here is an example where GDI is very slow with a specific font:
> [clsid2/mpc-hc#1095](https://github.com/clsid2/mpc-hc/issues/1095)

I tested the subtitle from https://github.com/clsid2/mpc-hc/issues/1095 with https://github.com/Masaiki/VSFilterMod/commit/c09ecfd91224699f6df19ef65f0bbc8cf49a4620 and found the same problem with MPC-HC internal subtitle render.
but it didn't occur on MPC-BE and Potplayer that also render subtitles with VSFilter.
So maybe it's not a problem of GDI.

**Comment by clsid2** [comment] 2021-05-16 14:54
The problem is only noticeable when the time it takes to render the subtitle is longer than the frame duration. On my system it takes 15ms so it slow but not slow enough to notice immediately.

You have to measure how long it takes to render the subtitle. You can do that easily with a call to GetTickCount64() before and after. And then for example do a debugbreak if the difference is more than a few milliseconds.

In the MPC-HC/VSFilter code the line that causes the delay is CloseFigure() in Rasterizer::EndPath()

**Comment by astiob** [comment] 2022-08-28 20:29
Oh God, please no. This will be an incompatible change, as you show and say yourself.

In particular, it seems the proposed patch (as much as it’s described as only a starting point) relies on `IDWriteFactory::CreateTextFormat` to _select_ a font, which is demonstrably incompatible with GDI’s `CreateFontIndirect`: you can read the nitty-gritty details [here](https://github.com/libass/libass/wiki/Fonts-across-platforms), and libass has [worked](https://github.com/libass/libass/commit/ac254eb826ec11e676223a9df560ce246927d063) [hard](https://github.com/libass/libass/pull/523) to avoid/minimize the differences.

Besides, the proposed patch makes no attempt at all to even handle `@font names` as far as I can see. DirectWrite does not support them natively.

The difference from libass in the screenshots shown here is because libass _sucks_ at emulating `@font names`. Essentially, this is [a libass bug](https://github.com/libass/libass/issues/619), and it has a decent chance of being fixed in future libass if we can just figure out what the hell is actually happening there.

So, vertical Source/Noto Sans has a smaller size. Subtitle authors account for that when creating the subtitles and [increase the `\fs`](https://github.com/Nekomoekissaten-SUB/Nekomoekissaten-poi-Subs/issues/3). If a newer VSFilter adjusts the size logic, those files that do this will start looking bad.

Plea to everyone: Just don’t touch VSFilter’s actual rendering logic, please. If you do, please make sure that it behaves the same as before in all cases that anyone had even a remote chance of triggering in a real subtitle file, and that it’s a change coordinated with libass and other VSFilter forks. And I ask this not as a developer, but as a user: I just want the subtitles I’ve collected that already look right to continue to look right, okay? Even if they use horrible quirks of ancient VSFilter, because that’s not the human viewer’s concern.

Finally: seeing as WordPad seems to show `Noto Sans CJK SC` and `@Noto Sans CJK SC` at the same size, it might be that this specific discrepancy _could_ be fixed by somehow adjusting VSFilter’s size logic when it requests the font from GDI (I have no idea how though), so in any case I believe the issue described in the original post and the issue’s _title_ are two distinct, independent things.

**Closed as completed** 2022-08-29 00:22 UTC
